# Generated by Django 3.2 on 2022-07-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
