# Generated by Django 3.2 on 2022-07-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_alter_template_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='css',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
