# Generated by Django 3.2 on 2022-07-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_auto_20220729_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
