# Generated by Django 3.2 on 2022-08-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0006_auto_20220802_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='bootstrap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='template',
            name='tailwind',
            field=models.BooleanField(default=False),
        ),
    ]
