# Generated by Django 3.2 on 2022-08-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0007_auto_20220805_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='bootstrap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='tailwind',
            field=models.BooleanField(default=False),
        ),
    ]
