# Generated by Django 3.2 on 2022-08-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0008_auto_20220805_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='script',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='style',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='script',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='style',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
    ]
