# Generated by Django 3.2 on 2022-08-05 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0009_auto_20220805_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='bootstrap',
        ),
        migrations.RemoveField(
            model_name='template',
            name='script',
        ),
        migrations.RemoveField(
            model_name='template',
            name='style',
        ),
        migrations.RemoveField(
            model_name='template',
            name='tailwind',
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=260, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_styles', to='builder.template')),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=260, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_scripts', to='builder.template')),
            ],
        ),
    ]
