# Generated by Django 3.2 on 2022-08-05 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0010_auto_20220805_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='bootstrap',
        ),
        migrations.RemoveField(
            model_name='page',
            name='script',
        ),
        migrations.RemoveField(
            model_name='page',
            name='style',
        ),
        migrations.RemoveField(
            model_name='page',
            name='tailwind',
        ),
        migrations.AddField(
            model_name='page',
            name='parent_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='builder.template'),
        ),
    ]
